### PR TITLE
update package to new version and framework

### PR DESCRIPTION
**Pull request by RyadaProductions**
This PR updates the following things:
- Normal libraries to .net standard 2.1
- Test projects to .net Standard 3.1
- FluentAssertions dependency to the latest version
- Fix breaking changes in the FluentAssertions Api
- Convert project files to the new csproj standard instead of the old one cleaning up a lot of clutter

Let me know if there are any concerns regarding this PR and I will happily improve it or give feedback on them.

### CODE REVIEW

**Comment by RyadaProductions** [comment]
@kevinkuszyk Would you be able to take a look at this?
Appveyor is failing due to having an outdated msbuild version from what i could see

**Comment by kevinkuszyk** [comment]
@RyadaProductions thanks for the contribution.  We were missing an `appveyor.yml` file to tell app veyor which version of VS to use.

Also, one little nit - I like to keep dependency versions as low as possible in libs, so that we don't force consumers to upgrade.  With that in mind, can you drop the FA dependency down to 5.0 and ninject to 3.3? 

Once that's done, I'm happy to merge and I'll ship it as version 1.5.

**Comment by RyadaProductions** [comment]
I have Adjusted the dependencies accordingly.

**Comment by kevinkuszyk** [comment]
@RyadaProductions thanks again for the contribution.  It's in 1.5.0 which should show up on nuget shortly.

**Pull request merged**
